# Here is an example training config file for 512x512 images.
channels: [32, 64, 128, 256, 512, 512, 512, 512]
tensorboard_log_dir: 'runs/stylegan2_512x512_with_pretrain_new_2'
tensorboard_image_interval: 20
checkpoint_dir: 'checkpoints/stylegan2_512x512_with_pretrain_new_2'
checkpoint_interval: 500
data_dir: /DATA2/wxr/anime_face
output_dir: train_output
gpu: [2]
g_file: /home/wxr/stylegan2_pytorch_backup/checkpoints/stylegan2_512x512_with_pretrain_new_2/29000_2021-01-20_01-02-12/G.pth
d_file: /home/wxr/stylegan2_pytorch_backup/checkpoints/stylegan2_512x512_with_pretrain_new_2/29000_2021-01-20_01-02-12/D.pth
iterations: 10000
batch_size: 4
