# Here is an example training config file for 512x512 images.
channels: [32, 64, 128, 256, 512, 512, 512, 512]
tensorboard_log_dir: 'runs/stylegan2_512x512_with_pretrain_new_2'
tensorboard_image_interval: 20
checkpoint_dir: 'checkpoints/stylegan2_512x512_with_pretrain_new_2'
checkpoint_interval: 500
data_dir: /DATA2/wxr/anime_face
output_dir: train_output
gpu: [0, 1, 2, 3]
g_file: /home/wxr/stylegan2_pytorch_backup/checkpoints/stylegan2_512x512_with_pretrain_new_2/10000_2020-12-22_03-42-54/G.pth
# g_file: /home/wxr/stylegan2_pytorch_backup/checkpoints/stylegan2_512x512_with_pretrain_new/8400_2020-12-21_09-48-35/G.pth
d_file: /home/wxr/stylegan2_pytorch_backup/checkpoints/stylegan2_512x512_with_pretrain_new_2/10000_2020-12-22_03-42-54/D.pth
iterations: 10000
